# Generated by Django 6.1.1 on 2026-09-28 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brawler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('raridade', models.CharField(max_length=50)),
                ('classe', models.CharField(max_length=50)),
                ('vida', models.IntegerField()),
                ('dano', models.IntegerField()),
                ('descricao', models.TextField()),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='brawlers/')),
            ],
        ),
    ]
