# Generated by Django 6.1.1 on 2026-09-30 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brawldex', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='brawler',
            name='imagem_url',
            field=models.URLField(blank=True, null=True, verbose_name='URL da imagem'),
        ),
    ]
